# Stage 1: Build the Angular application
FROM node:20 as build-stage

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json /app/

# Copy the entire Angular project's source code into the working directory
COPY . /app/

# Install the npm dependencies
RUN npm install

# Build the Angular application
RUN npm run build -- --output-path=/app/dist/plc-datalink-rfc1006-frontend

# Stage 2: Serve the Angular app using Nginx
FROM nginx:stable-alpine

# Remove default configurations
RUN rm /etc/nginx/conf.d/default.conf
RUN rm /etc/nginx/nginx.conf

# Copy custom Nginx configurations
COPY config/nginx-custom.conf /etc/nginx/conf.d/default.conf
COPY config/nginx-main.conf /etc/nginx/nginx.conf

# Copy the Angular application files from the build stage
COPY --from=build-stage /app/dist/plc-datalink-rfc1006-frontend /usr/share/nginx/html

# Expose the port Nginx is reachable on
EXPOSE 80

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
