version: '3.8'

services:
  plc-datalink-rfc1006-database:
    image: ${ACR_REGISTRY:-onconnecting.azurecr.io}/plc-datalink-rfc1006-database:${IMAGE_TAG:-latest}
    container_name: plc-datalink-rfc1006-database
    hostname: plc-datalink-rfc1006-database
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-password}
    volumes:
      - plc-datalink-rfc1006-database-data:/opt/couchdb/data
    networks:
      - plc-datalink-rfc1006-network

  plc-datalink-rfc1006-backend:
    image: ${ACR_REGISTRY:-onconnecting.azurecr.io}/plc-datalink-rfc1006-backend:${IMAGE_TAG:-latest}
    container_name: plc-datalink-rfc1006-backend
    hostname: plc-datalink-rfc1006-backend
    environment:
      - DATABASE_USER_NAME=${COUCHDB_USER:-admin}
      - DATABASE_SECRET_KEY=${COUCHDB_PASSWORD:-password}
    depends_on:
      - plc-datalink-rfc1006-database
    volumes:
      - plc-datalink-rfc1006-backend-data:/etc/telegraf
    networks:
      - plc-datalink-rfc1006-network

  plc-datalink-rfc1006-frontend:
    image: ${ACR_REGISTRY:-onconnecting.azurecr.io}/plc-datalink-rfc1006-frontend:${IMAGE_TAG:-latest}
    container_name: plc-datalink-rfc1006-frontend
    hostname: plc-datalink-rfc1006-frontend
    ports:
      - "80:80"
    depends_on:
      - plc-datalink-rfc1006-backend
    networks:
      - plc-datalink-rfc1006-network

networks:
  plc-datalink-rfc1006-network:
    name: plc-datalink-rfc1006-network
    driver: bridge

volumes:
  plc-datalink-rfc1006-backend-data:
    name: plc-datalink-rfc1006-backend-data
  plc-datalink-rfc1006-database-data:
    name: plc-datalink-rfc1006-database-data
