name: plc-datalink-rfc1006-dev

services:
  plc-datalink-rfc1006-database:
    image: ${LOCAL_REGISTRY:-192.168.0.121:5000}/plc-datalink-rfc1006-database:dev
    build:
      context: ./database
    container_name: plc-datalink-rfc1006-database
    hostname: plc-datalink-rfc1006-database
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER:-admin}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-password}
    volumes:
      - plc-datalink-rfc1006-database-data:/opt/couchdb/data
    networks:
      - plc-datalink-rfc1006-network

  plc-datalink-rfc1006-backend:
    image: ${LOCAL_REGISTRY:-192.168.0.121:5000}/plc-datalink-rfc1006-backend:dev
    build:
      context: ./backend
    container_name: plc-datalink-rfc1006-backend
    hostname: plc-datalink-rfc1006-backend
    environment:
      - DATABASE_USER_NAME=${COUCHDB_USER:-admin}
      - DATABASE_SECRET_KEY=${COUCHDB_PASSWORD:-password}
    depends_on:
      - plc-datalink-rfc1006-database
    volumes:
      - plc-datalink-rfc1006-backend-data:/etc/telegraf
    networks:
      - plc-datalink-rfc1006-network

  plc-datalink-rfc1006-frontend:
    image: ${LOCAL_REGISTRY:-192.168.0.121:5000}/plc-datalink-rfc1006-frontend:dev
    build:
      context: ./frontend
    container_name: plc-datalink-rfc1006-frontend
    hostname: plc-datalink-rfc1006-frontend
    ports:
      - "80:80"
    depends_on:
      - plc-datalink-rfc1006-backend
    networks:
      - plc-datalink-rfc1006-network

networks:
  plc-datalink-rfc1006-network:
    name: plc-datalink-rfc1006-network
    driver: bridge

volumes:
  plc-datalink-rfc1006-backend-data:
    name: plc-datalink-rfc1006-backend-data
  plc-datalink-rfc1006-database-data:
    name: plc-datalink-rfc1006-database-data
